openapi: 3.1.0
info:
  title: Offers API
  version: 1.0.0
  description: "German: \"Angebote\"\n\n- TOC\n\n## General\n- Request payloads to MOCO must be sent as valid JSON with a mandatory `Content-Type: application/json`-header. Responses are also sent as JSON.\n- All requests have to be [authenticated](authentication) with a key\n- Example responses showcase the happy case, i.e. usually the `200 OK` response\n- Collections are usually [paginated](#pagination)\n- Zapier triggers are **not** triggered for API requests\n- Timestamps `created_at` and `updated_at` are sent for all entities in UTC, as ISO8601 format.\n- For synchronization almost all resources can be filtered by `updated_after` passing a time in UTC, as ISO8601 format.\n- MOCO does not support any client-libraries at the moment. However, there are currently the following unofficial clients available, which you can use at your risk: [Python Client](https://github.com/sommalia/moco-wrapper)\n\n## Entities\nAll the entities exposed via the API can be found in their [respective sections](entities.md)\n\n## Client Implementations / API Wrappers\nHere's a list of API client implementations, not maintained by us. Feel free to open up a PR to point to your implementation so others can re-use it.\n\n| Language |                Repository                                                                            |\n| :------: | :-------------------------------------------------------------------------------------------------:  |\n| Python   | [https://github.com/sommalia/moco-wrapper](https://github.com/sommalia/moco-wrapper)                 |\n| PHP      | [https://github.com/mbs-hub/moco-php](https://github.com/mbs-hub/moco-php)                           |\n| Ruby     | [https://github.com/starsong-consulting/moco-ruby](https://github.com/starsong-consulting/moco-ruby) |\n\n## Impersonation\nBy default all requests are scoped to the authenticated user. Some resources cannot be provided with a `user_id` or similar, like `Activities` and `User Presences`. This reflects the behaviour in the UI, since every user can only create their own activities or presences. But you can login as another user provided that the authenticated user has permission to _Staff_. To achieve the same behaviour in the API, one can set the following x-header:\n\n`X-IMPERSONATE-USER-ID=123` (user id to act in behalf of)\n\n## Rate Limiting\nYou can expect to be able to send 120 requests per 2 minutes (~ 1 request per second). For the unlimited plan, its 1200 requests per 2 minutes (~ 10 per second). If you exceed this limit, the server responds with `429 Too Many Requests`.\n\n## Pagination\nResponses are paginated with a common default of 100 entries per page. In the HTTP response header, the current page, the entries per page and the number of total entries is reported. There is also a link header to links to the consecutive page.\n\n- **X-Page** \u2013 3\n- **X-Per-Page** \u2013 100\n- **X-Total** \u2013 415\n- **Link** \u2013 `<https://{domain}.mocoapp.com/api/v1/projects.json?page=4>; rel=\"next\"`\n\nIf there is not Link header with `rel=\"next\"`, the current page is the last page.\n\n## Errors and HTTP status codes\nThe MOCO-API is mostly conformant with the [general HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).\n\nHere are the most comment errors you will see:\n\n- **401 Unauthorized** - Check the error message in the response body\n- **403 Forbidden** - Check your [Authentication](#authentication) or your MOCO user permission\n- **404 Not Found** - Check that resource exists (maybe it was deleted in the meantime)\n- **422 Unprocessable Entity** - Check the provided error message in the response body\n- **429 Too Many Requests** - Check [Rate Limiting](#rate-limiting)\n\nSorting is controlled by the `sort_by` query parameter. Its value is the field name that should be sorted, followed by an optional sorting order (`asc` or `desc`, default is `asc`).\n\nExample:\n\n- `https://{domain}.mocoapp.com/api/v1/offers?sort_by=title desc`"
servers:
  -
    url: "https://{domain}.mocoapp.com/api/v1"
    description: Base server URL for the MOCO API.
tags:
  -
    name: Offers
    description: "German: \"Angebote\"\n\n- TOC"
components:
  securitySchemes:
    TokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "There's two ways to authenticate against MOCO:\n\n1. **User API key**. Can be found under the \"Integrations\" tab on the profile page.\n2. **Account API key**. Has to be created in Settings > Extensions > API & Webhooks, with either read-only or full access on all endpoints.\n\nBoth kinds of keys are provided as an Authorization header.\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/projects.json' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nThis key can also be requested via API for user-specific keys:\n\n```bash\ncurl -X POST \\\n  https://{domain}.mocoapp.com/api/v1/session \\\n  -H 'Accept: application/json' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"email\": \"max@muster.de\",\n    \"password\": \"secret\"\n  }'\n```\n\nIt's also possible to verify if the API key is still valid:\n\n```bash\ncurl https://{domain}.mocoapp.com/api/v1/session \\\n  -H 'Accept: application/json' \\\n  -H 'Content-Type: application/json'\n```\n\nIf the key is valid, the response code id `200 ok` and the body is:\n\n```json\n{\n  \"id\": 123,\n  \"uuid\": \"aec324a2-4832-11eb-b378-0242ac130002\"\n}\n```\n\notherwise the response code is `401 unauthorized`.\nThere are a few tools to try out the MOCO API. All the examples in this documentation use `curl` to demonstrate the API endpoint.\nA popular graphical UI for REST is [Postman](https://www.postman.com/). Here's an example request for the projects list including the authentication:\n\n![Postman example request](moco-api-postman.png \"Postman example request\")"
  parameters:
    Page:
      name: page
      in: query
      description: Pagination support as described in the general documentation.
      schema:
        type: integer
        minimum: 1
    PerPage:
      name: per_page
      in: query
      description: Number of items per page for paginated responses.
      schema:
        type: integer
        minimum: 1
    SortBy:
      name: sort_by
      in: query
      description: Sorting is controlled by the `sort_by` query parameter. Provide the field name and optional order (asc or desc).
      schema:
        type: string
    Ids:
      name: ids
      in: query
      description: "Usage: `GET /api/v1/entities?ids=123,456`\n\nAllows you to filter by comma-separated IDs and fetch multiple entities."
      schema:
        type: string
    UpdatedAfter:
      name: updated_after
      in: query
      description: "Usage: `GET /api/v1/entities?updated_after=2022-04-20T09:17:58Z` (ISO8601 timestamp)\n\nEnables you to give a timestamp for all entities that are created or updated after this timestamp, especially useful for synchronisation purposes.\n\nCombine it with a [webhook subscription](webhooks) on DELETE for the entity to have a complete synchronisation."
      schema:
        type: string
        format: "date-time"
    CustomProperties:
      name: custom_properties
      in: query
      description: "Allows you to filter entities by one or more custom fields. The filter for the custom fields is passed via the query-parameter `custom_properties`. To query entities that contain the value \"Automotive\" in a custom field named \"Sector\", the query would need to be as follows:\n\n`GET /api/v1/entities?custom_properties[Sector]=Automotive`\n\nFiltering by an unknown custom field will result in an empty result set!"
      schema:
        type: object
        additionalProperties: true
      style: deepObject
      explode: true
  schemas:
    ErrorResponse:
      type: object
      description: Generic error response body.
      properties:
        error:
          type: string
        message:
          type: string
      additionalProperties: true
    Offers:
      type: object
      description: "The offer representation contains among the standard fields:\n\n- custom properties\n- positions (items)\n- position types (\"title\", \"description\", \"item\", \"subtotal\", \"page-break\" or \"separator\")\n- subtotal_type: `part_total`, `sub_total`, `optional_part_total`, `optional_sub_total` (only relevant if type is `subtotal`)\n- vat (\"tax\", \"reverse_charge\", \"intra_eu\" (intra community trade, only applicable for accounts in the EU))\n- service_type (\"service\" for regular items, \"expense\" for additional services)\n\n```json\n{\n  \"id\": 273,\n  \"identifier\": \"A1704-042\",\n  \"invoice_id\": 1873491,\n  \"date\": \"2017-04-12\",\n  \"due_date\": \"2017-04-26\",\n  \"title\": \"Offer - User Management\",\n  \"recipient_address\": \"Beispiel GmbH\\nPeter Muster\\nBeispielstrasse 123\\n12345 Berlin\",\n  \"currency\": \"EUR\",\n  \"net_total\": 12750,\n  \"tax\": 19,\n  \"vat\": { \"tax\": 19.0, \"reverse_charge\": false, \"intra_eu\": false, \"active\": true, \"print_gross_total\": true, \"notice_tax_exemption\": \"\", \"notice_tax_exemption_alt\": \"\" },\n  \"gross_total\": 15172.5,\n  \"discount\": 10,\n  \"status\": \"created\",\n  \"salutation\": \"Hallo Peter<br><br>Folgende Aufw\u00e4nde sch\u00e4tzen wir f\u00fcr die Umsetzung der Komponenten:\",\n  \"footer\": \"F\u00fcr R\u00fcckfragen stehe ich dir jederzeit gerne zur Verf\u00fcgung.<br><br>Viele Gr\u00fcsse<br><br>Tobias\",\n  \"tags\": [\"Print\", \"Digital\"],\n  \"custom_properties\": {\n    \"ext-ref\": \"3421\"\n  },\n  \"company\": {\n    \"id\": 1234,\n    \"name\": \"Acme Corp.\"\n  },\n  \"project\": {\n    \"id\": 1234,\n    \"identifier\": \"P123\",\n    \"name\": \"A Project\"\n  },\n  \"deal\": {\n    \"id\": 1234,\n    \"name\": \"A Lead\"\n  },\n  \"user\": {\n    \"id\": 1234,\n    \"firstname\": \"Jane\",\n    \"lastname\": \"Doe\"\n  },\n  \"offer_confirmation\": {\n    \"id\": 1234,\n    \"date\": \"2022-12-12\",\n    \"title\": \"Offer confirmation\",\n    \"created_at\": \"2022-12-12T09:33:46Z\",\n    \"updated_at\": \"2022-12-12T09:33:46Z\"\n  },\n  \"customer_approval\": {\n    \"id\": 1234,\n    \"active\": true,\n    \"url\": \"https://mycompany.mocoapp.com/offers/1234/customer_approvals/ffbe642f6bdc65df7cb83a0d9459ece4\"\n  },\n  \"items\": [\n    {\n      \"id\": 29,\n      \"type\": \"item\",\n      \"title\": \"Project Setup\",\n      \"description\": null,\n      \"quantity\": 1,\n      \"unit\": \"d\",\n      \"unit_price\": 1500,\n      \"net_total\": 1500,\n      \"optional\": false\n      \"service_type\": \"service\",\n      \"revenue_category\": {\n        \"id\": 124,\n        \"name\": \"Hosting\",\n        \"revenue_account\": 30056,\n        \"cost_category\": \"HO1\"\n      }\n    },\n    {\n      \"id\": 30,\n      \"type\": \"item\",\n      \"title\": \"Master Data\",\n      \"description\": null,\n      \"quantity\": 3,\n      \"unit\": \"d\",\n      \"unit_price\": 1500,\n      \"net_total\": 4500,\n      \"optional\": false,\n      \"service_type\": \"service\",\n      \"revenue_category\": null\n    },\n    {\n      \"id\": 31,\n      \"type\": \"description\",\n      \"title\": null,\n      \"description\": \"Master data can be added.\",\n      \"quantity\": 0,\n      \"unit\": null,\n      \"unit_price\": 0,\n      \"net_total\": 0,\n      \"optional\": false,\n      \"service_type\": \"service\",\n      \"revenue_category\": null\n    },\n    {\n      \"id\": 34,\n      \"type\": \"item\",\n      \"title\": \"OAuth Provider (Single Sign On)\",\n      \"description\": null,\n      \"quantity\": 4,\n      \"unit\": \"d\",\n      \"unit_price\": 1500,\n      \"net_total\": 6000,\n      \"optional\": false,\n      \"service_type\": \"expense\",\n      \"revenue_category\": {\n        \"id\": 123,\n        \"name\": \"Software-Entwicklung\",\n        \"revenue_account\": 30055,\n        \"cost_category\": \"SW1\"\n      }\n    },\n    {\n      \"id\": 35,\n      \"type\": \"description\",\n      \"title\": null,\n      \"description\": \"This component runs centrally and provides an OAuth Provider.<br>Other applications can access this authorization service.\",\n      \"quantity\": 0,\n      \"unit\": null,\n      \"unit_price\": 0,\n      \"net_total\": 0,\n      \"optional\": false,\n      \"service_type\": \"service\",\n      \"revenue_category\": null\n    },\n    {\n      \"id\": 38,\n      \"type\": \"item\",\n      \"title\": \"Project Management / Communication / Hand-Over\",\n      \"description\": null,\n      \"quantity\": 0.5,\n      \"unit\": \"d\",\n      \"unit_price\": 1500,\n      \"net_total\": 750,\n      \"optional\": false,\n      \"service_type\": \"service\"\n      \"revenue_category\": {\n        \"id\": 126,\n        \"name\": \"Projektleitung\",\n        \"revenue_account\": 30058,\n        \"cost_category\": \"PM1\"\n      }\n    }\n  ],\n  \"created_at\": \"2018-10-17T09:33:46Z\",\n  \"updated_at\": \"2018-10-17T09:33:46Z\"\n}\n```\n\nCustom fields reference:\nMOCO supports saving custom fields to many of its resources. These custom fields are readable and writable via the `custom_properties` field.\n\n Custom fields must first be defined in the MOCO settings.\n\n The size of the custom_properties field is limitted to 12 kB.\n\n```json\n\"custom_properties\": {\n    \"UID\": \"123-UID-456\",\n    \"Line of business\": \"Automotive\"\n}\n```\n\nParameters are sent with their name as key:\n\n```bash\ncurl -X POST \\\n  https://{domain}.mocoapp.com/api/v1/customers \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n    \"name\": \"Beispiel AG\",\n    \"currency\": \"CHF\",\n    \"custom_properties\": {\n      \"Line of business\": \"Automotive\"\n    }\n  }'\n```\n\nAll values are encoded as strings, expect for Multiple Choice, which is encoded as an array.\n\n```bash\ncurl -X POST \\\n  https://{domain}.mocoapp.com/api/v1/customers \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"custom_properties\": {\n          \"Line of business\": [\"Automotive\", \"Banking\"]\n        }\n      }'\n```\n\n- Single-line input \u2013 \"Automotive\"\n- Mehrzeilige Eingabe \u2013 \"A multiline input...\"\n- Link \u2013 \"https://www...\"\n- Date \u2013 \"2021-12-31\"\n- Yes/No \u2013 \"0\", \"1\" (0 = No, 1 = Yes)\n- Single choice \u2013 \"Value\"\n- Multiple choice \u2013 [\"Value 1\", \"Value 2\"]\n\n\nThe provided custom properties are merged with the existing custom properties of the entity. That is, only the provided custom properties are updated and the other custom properties of the entity are left unchanged.\nIt is possible to filter entities by custom fields, as described in\n[Global filters](./entities#filter-by-custom-fields-\u2013-custom_properties)"
security:
  -
    TokenAuth:
      []
paths:
  /offers:
    get:
      summary: GET /offers
      description: "Retrieve all offers:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nThis returns an array with complete offer information (see Attributes), except: `salutation`, `footer` and `items`.\n\nOffers can be sorted by: `date`, `created_at` and `title`:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers?sort=date' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nAdditionally, these parameters can be supplied:\n\n- [Global filters apply](../entities#global-filters)\n- **status** \u2013 (\"created\", \"sent\", \"accepted\", \"partially_billed\", \"billed\", \"archived\")\n- **from** \u2013 \"2018-01-01\"\n- **to** \u2013 \"2018-01-31\"\n- **identifier** \u2013 \"A1903-003\"\n- **deal_id** \u2013 \"123,456\" (deal ID for offers on this deal, single or comma-separated values)\n- **project_id** \u2013 \"123,456\" (project ID for offers on this project, single or comma-separated values)\n- **company_id** \u2013 \"123,456\" (company ID for offers on this project, single or comma-separated values)"
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      parameters:
        -
          $ref: "#/components/parameters/Ids"
        -
          $ref: "#/components/parameters/UpdatedAfter"
        -
          $ref: "#/components/parameters/CustomProperties"
        -
          $ref: "#/components/parameters/Page"
        -
          $ref: "#/components/parameters/PerPage"
        -
          $ref: "#/components/parameters/SortBy"
      responses:
        200:
          description: "Retrieve all offers:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nThis returns an array with complete offer information (see Attributes), except: `salutation`, `footer` and `items`."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Offers"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: getOffersOffers
    post:
      summary: POST /offers
      description: "Create an offer:\n\n```bash\ncurl -X POST \\\n  'https://{domain}.mocoapp.com/api/v1/offers' \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"deal_id\": 123,\n        \"recipient_address\": \"Acme\\r\\nPark Avenue\",\n        \"date\": \"2019-05-10\",\n        \"due_date\": \"2019-06-08\",\n        \"title\": \"Offer - Shop Locator\",\n        \"salutation\": \"Hey\",\n        \"tax\": 8.0,\n        \"discount\": 0.0,\n        \"footer\": \"Bye\",\n        \"internal_contact_id\": 1234,\n        \"items\":[\n            {\"type\":\"title\",\"title\":\"Stunden\"},\n            {\"type\":\"description\",\"description\":\"Aufstellung \u00fcber geleistete Arbeiten\"},\n            {\"type\":\"item\",\"title\":\"MailChimp Einrichtung\",\"quantity\":1,\"unit\":\"Std\",\"unit_price\":100.0}\n            ]}'\n```\n\nMandatory fields are marked with a star (\\*):\n\n- **company_id** \u2013 123456 (ID of the associated company), is disregarded and set to the company of the project if project_id is provided\n- **deal_id** \u2013 123456 (ID of the associated deal)\n- **project_id** \u2013 123456 (ID of the associated project)\n- **recipient_address\\*** \u2013 \"My customer...\"\n- **date\\*** \u2013 \"2018-09-17\"\n- **due_date\\*** \u2013 \"2018-10-16\"\n- **title\\*** \u2013 \"Offer\"\n- **tax\\*** \u2013 8.0\n- **currency\\** \u2013 \"CHF\" (a valid currency of the account), must match the currency of provided project and deal, only required if no company_id, deal_id and project_id is provided\n- **items\\*** \u2013 positions (see [attributes](#attributes))\n- **change_address** \u2013 address propagation (\"offer\", \"customer\"), default is \"offer\"\n- **salutation** (salutation text)\n- **footer** (footer text)\n- **discount** \u2013 10 (discount in percent)\n- **contact_id** \u2013 123456 (ID of the associated contact at customer)\n- **internal_contact_id** - 1234 (ID of an internal user)\n- **tags** \u2013 [\"Retail\"]\n- **custom_properties** \u2013 {\"ext-ref\": \"3421\"}\n- **print_detail_columns**  - true (Hide/Display 'quantity, unit, price'). Optional property, which defaults to the global account layout setting"
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        201:
          description: "Create an offer:\n\n```bash\ncurl -X POST \\\n  'https://{domain}.mocoapp.com/api/v1/offers' \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"deal_id\": 123,\n        \"recipient_address\": \"Acme\\r\\nPark Avenue\",\n        \"date\": \"2019-05-10\",\n        \"due_date\": \"2019-06-08\",\n        \"title\": \"Offer - Shop Locator\",\n        \"salutation\": \"Hey\",\n        \"tax\": 8.0,\n        \"discount\": 0.0,\n        \"footer\": \"Bye\",\n        \"internal_contact_id\": 1234,\n        \"items\":[\n            {\"type\":\"title\",\"title\":\"Stunden\"},\n            {\"type\":\"description\",\"description\":\"Aufstellung \u00fcber geleistete Arbeiten\"},\n            {\"type\":\"item\",\"title\":\"MailChimp Einrichtung\",\"quantity\":1,\"unit\":\"Std\",\"unit_price\":100.0}\n            ]}'\n```\n\nMandatory fields are marked with a star (\\*):\n\n- **company_id** \u2013 123456 (ID of the associated company), is disregarded and set to the company of the project if project_id is provided\n- **deal_id** \u2013 123456 (ID of the associated deal)\n- **project_id** \u2013 123456 (ID of the associated project)\n- **recipient_address\\*** \u2013 \"My customer...\"\n- **date\\*** \u2013 \"2018-09-17\"\n- **due_date\\*** \u2013 \"2018-10-16\"\n- **title\\*** \u2013 \"Offer\"\n- **tax\\*** \u2013 8.0\n- **currency\\** \u2013 \"CHF\" (a valid currency of the account), must match the currency of provided project and deal, only required if no company_id, deal_id and project_id is provided\n- **items\\*** \u2013 positions (see [attributes](#attributes))\n- **change_address** \u2013 address propagation (\"offer\", \"customer\"), default is \"offer\"\n- **salutation** (salutation text)\n- **footer** (footer text)\n- **discount** \u2013 10 (discount in percent)\n- **contact_id** \u2013 123456 (ID of the associated contact at customer)\n- **internal_contact_id** - 1234 (ID of an internal user)\n- **tags** \u2013 [\"Retail\"]\n- **custom_properties** \u2013 {\"ext-ref\": \"3421\"}\n- **print_detail_columns**  - true (Hide/Display 'quantity, unit, price')."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
              examples:
                example:
                  value:
                    deal_id: 123
                    recipient_address: "Acme\r\nPark Avenue"
                    date: "2019-05-10"
                    due_date: "2019-06-08"
                    title: "Offer - Shop Locator"
                    salutation: Hey
                    tax: 8.0
                    discount: 0.0
                    footer: Bye
                    internal_contact_id: 1234
                    items:
                      -
                        type: title
                        title: Stunden
                      -
                        type: description
                        description: Aufstellung über geleistete Arbeiten
                      -
                        type: item
                        title: MailChimp Einrichtung
                        quantity: 1
                        unit: Std
                        unit_price: 100.0
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Offers"
            examples:
              example:
                value:
                  deal_id: 123
                  recipient_address: "Acme\r\nPark Avenue"
                  date: "2019-05-10"
                  due_date: "2019-06-08"
                  title: "Offer - Shop Locator"
                  salutation: Hey
                  tax: 8.0
                  discount: 0.0
                  footer: Bye
                  internal_contact_id: 1234
                  items:
                    -
                      type: title
                      title: Stunden
                    -
                      type: description
                      description: Aufstellung über geleistete Arbeiten
                    -
                      type: item
                      title: MailChimp Einrichtung
                      quantity: 1
                      unit: Std
                      unit_price: 100.0
      operationId: postOffersOffers
  /offers/{id}:
    get:
      summary: "GET /offers/{id}"
      description: "Retrieve a single offer:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nThis returns a single offer representation, including internal contact and positions."
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        200:
          description: "Retrieve a single offer:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nThis returns a single offer representation, including internal contact and positions."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: getOffersIdOffers
  /offers/{id}.pdf:
    get:
      summary: "GET /offers/{id}.pdf"
      description: "Retrieve a single offer document:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}.pdf' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nAdditionally, the following parameters can be supplied:\n\n- **letter_paper_id** \u2013 (letter paper ID, default: White)\n\nThis returns this offers's PDF document."
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        200:
          description: "Retrieve a single offer document:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}.pdf' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nAdditionally, the following parameters can be supplied:\n\n- **letter_paper_id** \u2013 (letter paper ID, default: White)\n\nThis returns this offers's PDF document."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: getOffersId.PdfOffers
  /offers/{id}/assign:
    put:
      summary: "PUT /offers/{id}/assign"
      description: "Assign an offer to a company, project, and/or deal.\n\n```bash\ncurl -X PUT \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}/assign' \\\n  -H 'authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"company_id\": 1234,\n        \"project_id\": 2345,\n        \"deal_id\": 3456\n      }'\n```\n\nIf a `project_id` is set, the project's `company_id` is also set on this offer. If the company does not match the project's company, the project company overrides the given `company_id`."
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        200:
          description: "Assign an offer to a company, project, and/or deal."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
              examples:
                example:
                  value:
                    company_id: 1234
                    project_id: 2345
                    deal_id: 3456
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Offers"
            examples:
              example:
                value:
                  company_id: 1234
                  project_id: 2345
                  deal_id: 3456
      operationId: putOffersIdAssignOffers
  /offers/{id}/update_status:
    put:
      summary: "PUT /offers/{id}/update_status"
      description: "Update an offer status:\n\n```bash\ncurl -X PUT \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}/update_status' \\\n  -H 'authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"status\": \"billed\"\n      }'\n```\n\nThe following states are valid: \"created\", \"sent\", \"accepted\", \"partially_billed\", \"billed\", \"archived\"."
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        200:
          description: "Update an offer status:\n\n```bash\ncurl -X PUT \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}/update_status' \\\n  -H 'authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"status\": \"billed\"\n      }'\n```\n\nThe following states are valid: \"created\", \"sent\", \"accepted\", \"partially_billed\", \"billed\", \"archived\"."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
              examples:
                example:
                  value:
                    status: billed
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Offers"
            examples:
              example:
                value:
                  status: billed
      operationId: putOffersIdUpdate_StatusOffers
  /offers/{id}/send_email:
    post:
      summary: "POST /offers/{id}/send_email"
      description: "Send the offer by email:\n\n```bash\ncurl -X POST \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}/send_email' \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"emails_to\": \"somebody@example.com\",\n        \"subject\": \"Offer\",\n        \"text\": \"Kind regards\"\n      }'\n```\n\nMandatory fields are marked with a star (\\*):\n\n- **subject\\*** \u2013 \"Offer\",\n- **text\\*** \u2013 \"Kind regards\"\n- **emails_to** \u2013 \"somebody@example.com;info@example.com\" (list of addresses separated by _;_). To use default recipients, see information below.\n- **emails_cc** \u2013 \"somebodyelse@example.com\" (list of addresses separated by _;_)\n- **emails_bcc** \u2013 \"somebody@partner.example.com\" (list of addresses separated by _;_)\n\n\ud83d\udec8 If you want to send emails to the default recipients configured on the customer or set as a contact, leave `emails_to`, `emails_cc` and `emails_bcc` empty. `emails_to` always needs to be provided, either via the default recipients or as a given value. In the response, the recipients selected are returned."
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        201:
          description: "Send the offer by email:\n\n```bash\ncurl -X POST \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}/send_email' \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"emails_to\": \"somebody@example.com\",\n        \"subject\": \"Offer\",\n        \"text\": \"Kind regards\"\n      }'\n```\n\nMandatory fields are marked with a star (\\*):\n\n- **subject\\*** \u2013 \"Offer\",\n- **text\\*** \u2013 \"Kind regards\"\n- **emails_to** \u2013 \"somebody@example.com;info@example.com\" (list of addresses separated by _;_)."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
              examples:
                example:
                  value:
                    emails_to: somebody@example.com
                    subject: Offer
                    text: Kind regards
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Offers"
            examples:
              example:
                value:
                  emails_to: somebody@example.com
                  subject: Offer
                  text: Kind regards
      operationId: postOffersIdSend_EmailOffers
  /offers/{id}/attachments:
    get:
      summary: "GET /offers/{id}/attachments"
      description: "List all attachments for this offer:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{offer_id}/attachments' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nProvide the payload base64 encoded."
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        200:
          description: "List all attachments for this offer:\n\n```bash\ncurl -X GET \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{offer_id}/attachments' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'\n```\n\nProvide the payload base64 encoded."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: getOffersIdAttachmentsOffers
    post:
      summary: "POST /offers/{id}/attachments"
      description: "Add attachment PDF to offer:\n\n```bash\ncurl -X POST \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}/attachments' \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"attachment\": {\n          \"filename\": \"attachment.pdf\",\n          \"base64\": \"JVBERi0xLjQKJeLjz9MKNCAwIG9iago8PC9GaWx...\"\n        }\n      }'\n```\n\nProvide the payload base64 encoded."
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        201:
          description: "Add attachment PDF to offer:\n\n```bash\ncurl -X POST \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{id}/attachments' \\\n  -H 'Authorization: Token token=YOUR_API_KEY' \\\n  -H 'Content-Type: application/json' \\\n  -d '{\n        \"attachment\": {\n          \"filename\": \"attachment.pdf\",\n          \"base64\": \"JVBERi0xLjQKJeLjz9MKNCAwIG9iago8PC9GaWx...\"\n        }\n      }'\n```\n\nProvide the payload base64 encoded."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Offers"
              examples:
                example:
                  value:
                    attachment:
                      filename: attachment.pdf
                      base64: JVBERi0xLjQKJeLjz9MKNCAwIG9iago8PC9GaWx...
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Offers"
            examples:
              example:
                value:
                  attachment:
                    filename: attachment.pdf
                    base64: JVBERi0xLjQKJeLjz9MKNCAwIG9iago8PC9GaWx...
      operationId: postOffersIdAttachmentsOffers
  /offers/{offer_id}/attachments/{id}:
    delete:
      summary: "DELETE /offers/{offer_id}/attachments/{id}"
      description: "Remove attachment from offer:\n\n```bash\ncurl -X DELETE \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{offer_id}/attachments/{id}' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'"
      tags:
        - Offers
      security:
        -
          TokenAuth:
            []
      responses:
        204:
          description: "Remove attachment from offer:\n\n```bash\ncurl -X DELETE \\\n  'https://{domain}.mocoapp.com/api/v1/offers/{offer_id}/attachments/{id}' \\\n  -H 'Authorization: Token token=YOUR_API_KEY'"
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      operationId: deleteOffersOffer_IdAttachmentsIdOffers
